### ISSUE TITLE
Error occurred when executing Fooocus PreKSampler:  'ModelPatcher' object has no attribute 'current_loaded_device'

### ISSUE THREAD

**Issue by shikasensei-dev** [Seedsa/Fooocus_Nodes#32]
Hello, first of all, I wanted to thank you for the excellent work you did; it has been very helpful to me. However, since yesterday, the nodes haven't been working for me. I even reinstalled ComfyUI, but it didn't help.

Error occurred when executing Fooocus PreKSampler:

'ModelPatcher' object has no attribute 'current_loaded_device'

File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 423, in fooocus_preKSampler
pipeline.refresh_everything(
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\default_pipeline.py", line 234, in refresh_everything
refresh_base_model(base_model_name)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\default_pipeline.py", line 70, in refresh_base_model
model_base = core.load_model(filename)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\core.py", line 147, in load_model
unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\ldm_patched\modules\sd.py", line 441, in load_checkpoint_guess_config
model = load_checkpoint_guess_config_without_cache(ckpt_path, output_vae, output_clip, output_clipvision, embedding_directory, output_model)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\ldm_patched\modules\sd.py", line 501, in load_checkpoint_guess_config_without_cache
model_management.load_model_gpu(model_patcher)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 474, in load_model_gpu
return load_models_gpu([model])
File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\patch.py", line 447, in patched_load_models_gpu
y = comfy.model_management.load_models_gpu_origin(*args, **kwargs)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 439, in load_models_gpu
total_memory_required[loaded_model.device] = total_memory_required.get(loaded_model.device, 0) + loaded_model.model_memory_required(loaded_model.device)
File "C:\StabilityMatrix\Data\Packages\ComfyUI\comfy\model_management.py", line 277, in model_memory_required
if device == self.model.current_loaded_device():

**Comment by Seedsa** [comment]
it should be fixed now

**Comment by AusafMo** [comment]
> it should be fixed now

hey, thanks for the work.

I am still getting the same error though:
things i've tried:
- updated comfyUI
- pulled the latest version of this repo

```Error occurred when executing Fooocus PreKSampler:

'ModelPatcher' object has no attribute 'loaded_size'

File "/root/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/root/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/root/ComfyUI/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 423, in fooocus_preKSampler
pipeline.refresh_everything(
File "/root/.pyenv/versions/COMFY/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/COMFY/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/ComfyUI/custom_nodes/Fooocus_Nodes/py/modules/default_pipeline.py", line 249, in refresh_everything
prepare_text_encoder(async_call=True)
File "/root/.pyenv/versions/COMFY/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/COMFY/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/ComfyUI/custom_nodes/Fooocus_Nodes/py/modules/default_pipeline.py", line 212, in prepare_text_encoder
comfy.model_management.load_models_gpu([final_clip.patcher, final_expansion.patcher])
File "/root/ComfyUI/custom_nodes/Fooocus_Nodes/py/modules/patch.py", line 447, in patched_load_models_gpu
y = comfy.model_management.load_models_gpu_origin(*args, **kwargs)
File "/root/ComfyUI/comfy/model_management.py", line 526, in load_models_gpu
cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
File "/root/ComfyUI/comfy/model_management.py", line 311, in model_load
if self.model.loaded_size() > 0:
```


I am trying to use inpainting workflow.

**Comment by AIGC404** [comment]
@Seedsa  

After I updated yesterday's commit, there were exceptions in the operation, and the exceptions are as follows

Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by Seedsa** [comment]
> @Seedsa
> 
> After I updated yesterday's commit, there were exceptions in the operation, and the exceptions are as follows
> 
> Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

Try to update ComyUI

**Comment by AIGC404** [comment]
> > @Seedsa
> > After I updated yesterday's commit, there were exceptions in the operation, and the exceptions are as follows
> > Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
> 
> Try to update ComyUI

The comfyui version has been updated to the latest version, but problems still exist
Commit:  0f9c2a78224ce3179c773fe3af63722f438b0613

**Comment by AIGC404** [comment]
Error occurred when executing Fooocus PreKSampler:

Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

File "D:\ai-tools-all\ComfyUI-aki-v1.1\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ai-tools-all\ComfyUI-aki-v1.1\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 494, in fooocus_preKSampler
expansion = pipeline.final_expansion(t['task_prompt'], t['task_seed'])
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\custom_nodes\Fooocus_Nodes\py\extras\expansion.py", line 117, in __call__
features = self.model.generate(**tokenized_kwargs,
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\generation\utils.py", line 1622, in generate
result = self._sample(
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\generation\utils.py", line 2791, in _sample
outputs = self(
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 1305, in forward
transformer_outputs = self.transformer(
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 1068, in forward
inputs_embeds = self.wte(input_ids)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\modules\sparse.py", line 163, in forward
return F.embedding(
File "D:\ai-tools-all\ComfyUI-aki-v1.1\python\lib\site-packages\torch\nn\functional.py", line 2264, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
